### PR TITLE
Delete test

### PR DESCRIPTION
**Pull request by 0xWDG**

### CODE REVIEW

**Comment by aurora-care-bear** [comment]
Thanks for submitting a pull request!
We will review it as soon as possible.

**Comment by 0xWDG** [comment]
@aurora-editor-bot please reject this pr

**Review by aurora-care-bear — CHANGES_REQUESTED** [review]
Rejected on behalf of @0xWDG

**Comment by 0xWDG** [comment]
@aurora-editor-bot please accept this pr

**Review by aurora-care-bear — APPROVED** [review]
Approved on behalf of @0xWDG

**Pull request merged**
